# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 518ed8b60bbea63ae3715e8254da6cb996f193e7e184ecd6f377182e0ff83fa4f06c3cfbe96704610690d29532d5a1256eaaa4b855c188d84a3ad73f2399ad2c

test:
  secret_key_base: 29be77c1138f9ab1b630605da3afc494deaad09793509b6749e53a2592fb16fdddff96f015c1c00e5d8b1d94bcfe8dc27bfbd98255b69d3aa1b2be36ca8228ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
